// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsbGwgi24hIvey_6taCe1fyGeLI5xpf4',
    appId: '1:483580376847:web:0ddaa518f7170949e2307a',
    messagingSenderId: '483580376847',
    projectId: 'ecommerceapp-fdad0',
    authDomain: 'ecommerceapp-fdad0.firebaseapp.com',
    storageBucket: 'ecommerceapp-fdad0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMZx_D2_bOmR1EqLraHr19s79nQDdiB8',
    appId: '1:483580376847:android:f985e9d16dec073be2307a',
    messagingSenderId: '483580376847',
    projectId: 'ecommerceapp-fdad0',
    storageBucket: 'ecommerceapp-fdad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZZA8SSVrK13Z7AGOHbtdxojCcjS7qnM',
    appId: '1:483580376847:ios:fa547294d94935d8e2307a',
    messagingSenderId: '483580376847',
    projectId: 'ecommerceapp-fdad0',
    storageBucket: 'ecommerceapp-fdad0.firebasestorage.app',
    androidClientId: '483580376847-5routkg7ehmhunrgc9b2rnthsb4v881v.apps.googleusercontent.com',
    iosClientId: '483580376847-7mpq2v4ae79oade19v157u12bo4pt5d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}